### ISSUE TITLE
[要望]ユーザー登録後に「メルアド認証してくれ」って教えて欲しい

### ISSUE THREAD

**Issue by hidesys** [fuyu77/utakata#11]
ユーザー登録後に、「メールを送ったので認証リンクを踏んでメルアド認証をして欲しい」ってWebの画面で教えて欲しい。
`flash`の`notice`とか使うといいかも知れません。

**Comment by fuyu77** [comment]
「登録する」ボタンを押した後にこれが出るようにしてあったのですが、表示されませんでしたか？（今日の15時までテスト期間にすると伝えましたが、今も触っていただいて大丈夫な状態です）
![utakata](https://user-images.githubusercontent.com/19484918/41507697-1c9d0986-7273-11e8-8074-134ce83d988e.jpeg)

**Comment by hidesys** [comment]
あ。すいません。出ていたみたいです……。
