### ISSUE TITLE
通知をリアルタイムにする

### ISSUE THREAD

**Issue by tan-t** [fuyu77/utakata#14]
websocketでリアルタイムに出せると承認欲求的には満たしやすく、定着率が上がりそう

https://qiita.com/sasurai_usagi3/items/37f1268621a258864f46

https://qiita.com/sasurai_usagi3/items/75a30cc0d2d0faa9dfe8

この辺り

**Comment by fuyu77** [comment]
リアルタイム通知をどうやってやるのか分かってなかったので、参考記事教えていただけるのはありがたいです。実装してみたいと思います。
