### ISSUE TITLE
[要望・提案]ルビのタグ打つのが面倒

### ISSUE THREAD

**Issue by tan-t** [fuyu77/utakata#4]
ボタン押したらタグが補完されるとかするか、あるいは何らかの記法に対応してもらえると便利だと思いました。  
特にスマホから直で打つのはほぼ無理感があります。

**Comment by fuyu77** [comment]
ルビのテンプレをフェームに挿入するボタンは作れそうですね。

**Comment by tan-t** [comment]
プルリク送ってみた
