### ISSUE TITLE
短歌作成時、ルビを適切に振れていない人がいる

### ISSUE THREAD

**Issue by usk94** [fuyu77/utakata#464]
### 事象
以下のようにルビが文字の横に来ていないパターンがありました。

<img width="40" alt="image" src="https://github.com/fuyu77/utakata/assets/66470480/ca37ce00-1755-447d-8b1f-ca9fb09cd319">

### 原因
おそらく作成時、`ruby`タグや`rt`タグの要領をうまく掴めず、以下のように対象の文字を`ruby`タグの外に出したのでは、と思いました。
<img width="895" alt="image" src="https://github.com/fuyu77/utakata/assets/66470480/f4ee060c-10ac-4331-b6f5-e64a01a194dc">

### 提案
作成時に、ルビを振ろうとしているにもかかわらず`ruby`タグと`rt`タグの間に文字列が存在しない場合は、バリデーションしてエラーを出してあげるか、ルビが適切に振れていませんがよろしいですか？とポップアップ的なものを出してあげても良いのかなと思いました。

**Comment by usk94** [comment]
@fuyu77 
ご返信いただき、ありがとうございます！

> それと、そもそも投稿フォーム上のルビの説明が分かりづらいのも原因な気がする

そうですね。まずここな気がします。
ルビの文字をタグで当てがうにあたって、書き方の例を1つ記載するなどよいのかなと思いました。

> 文字列を選択せずに「ルビ」ボタンを押しちゃってるっぽい

このパターンもあると思いますし、併せて、文字列を選択してルビボタンを押したが、なんかよくわからないままルビ対象の文字をrubyの外側に出してしまうパターンもあると思ったのですよね。
書き方の例の話と少し被りますが、rubyタグのシンタックス・作法をユーザーは基本的に知らないと思うので。

> 後からのバリデーションだと直し方が分かりづらい

これって環さんが挙げてくださったパターンでも、私が挙げたパターンでも、`oldText.slice(start, end)}`が空文字列かで判定できるのかなと思ったのですが、難しそうですかね？

**Comment by fuyu77** [comment]
@usk94 
- https://github.com/fuyu77/utakata/pull/468

取り敢えず文言調整してリリースしてみました。

あとは追加の入力補助をやるかやらないかですよね。

まずバリデーションについてなのですが、裏技的なテクニックとして、意図的に空文字にルビだけ入力する表現技法があり得るので、一律にエラーで弾くのはやらない方針としたいです。

https://utakatanka.jp/tanka/95510

例えばこの短歌とかはわざと空文字にルビを振っているようで。

なので、@usk94 さんの

> ルビが適切に振れていませんがよろしいですか？とポップアップ的なものを出し

この案か、または私の提案した文字選択なしで「ルビ」ボタンを押せないようにするような処理を入れるのが対応案としてあり得ると思います。

また、気軽に使えるシンプルなサイトという点を優先して、文言変更のみでCloseする判断もあり得ますね。

**Comment by usk94** [comment]
@fuyu77 
> 例えばこの短歌とかはわざと空文字にルビを振っているようで。

この例はおもしろいですねw
早速文言調整いただき、ありがとうございます！

> また、気軽に使えるシンプルなサイトという点を優先して

たしかに、ポップアップを出したが結局のところどうすればいいかわからず投稿に億劫になってしまう可能性もあるかもしれません。
また特定の条件下でルビボタンを押せなくするのも気軽さを若干損なう気はするので、おっしゃる通り、一旦実施いただいた文言調整で十分かもしれませんね。

検討と修正をしてくださり、ありがとうございました！

**Comment by fuyu77** [comment]
@usk94 
ありがとうございます！では今回はこれで完了ってことにしますね。

またIssueとかPRの投稿はいつでも歓迎します！
