### ISSUE TITLE
[minor][クロスブラウザ]IEだと投稿画面のレイアウトが終わる

### ISSUE THREAD

**Issue by tan-t** [fuyu77/utakata#6]
まあIEは滅ぼしましょう。  
推奨ブラウザは明記したほうがいいかもです。

![image](https://user-images.githubusercontent.com/22813443/41495682-ad406cc4-7167-11e8-9859-a242f051f284.png)

**Comment by fuyu77** [comment]
IE対応はキツいですね。推奨ブラウザは明記したいと思います。
