### ISSUE TITLE
[normal][クロスブラウザ]firefox(quantum 60.0.2)でもレイアウトが怪しい。

### ISSUE THREAD

**Issue by tan-t** [fuyu77/utakata#7]
firefox対応はやっといたほうが得？  
margin-autoはブラウザによって解釈が違うっぽいです。  

![image](https://user-images.githubusercontent.com/22813443/41495793-51db46bc-716a-11e8-8913-d68e6090ffe9.png)

**Comment by fuyu77** [comment]
おお、これは対応した方が良いですね。ちなみにIEでもここ以外は大丈夫なのでしょうか？

**Comment by tan-t** [comment]
フォントが微妙なの以外は違和感なしです

**Comment by tan-t** [comment]
IEでnoteとか開くときれいなフォントで出るのでなんかアプリ側の問題なんじゃねと思ってます、フォントは門外漢なのでよくわからないですが。。。

**Comment by tan-t** [comment]
参考_フォント
![image](https://user-images.githubusercontent.com/22813443/41495828-9122f5a8-716b-11e8-919e-28c6e4b2d8f7.png)

**Comment by fuyu77** [comment]
これはMSP明朝っぽいですね。フォント指定すればマシになるかも知れません。
